//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackenBilletera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia
    {
        public int idTransferencia { get; set; }
        public System.DateTime fecha { get; set; }
        public int monto { get; set; }
        public int idUsuario { get; set; }
        public int idDestino { get; set; }
        public int idMoneda { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
