//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilleteraMVCAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FondoComun
    {
        public int idFondoComun { get; set; }
        public string nombre { get; set; }
        public string monto { get; set; }
        public int Usuario { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
    }
}
