//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilleteraMVCAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int id_movimiento { get; set; }
        public System.DateTime fec_movimiento { get; set; }
        public int Tipo { get; set; }
        public int idCliente { get; set; }
        public int monto { get; set; }
        public int num_comprobante { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Tipo_Mov Tipo_Mov { get; set; }
    }
}
