//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackenBilletera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int idFactura { get; set; }
        public Nullable<int> monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idServicio { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
